/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TYPES_H_RPCGEN
#define _TYPES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum call_type {
	GET = 0,
	QUIT = 1,
};
typedef enum call_type call_type;

enum response_msg {
	OK = 0,
	ERR = 1,
};
typedef enum response_msg response_msg;

struct call_msg {
	call_type ctype;
	union {
		char *filename;
	} call_msg_u;
};
typedef struct call_msg call_msg;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_call_type (XDR *, call_type*);
extern  bool_t xdr_response_msg (XDR *, response_msg*);
extern  bool_t xdr_call_msg (XDR *, call_msg*);

#else /* K&R C */
extern bool_t xdr_call_type ();
extern bool_t xdr_response_msg ();
extern bool_t xdr_call_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TYPES_H_RPCGEN */
