/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "types1.h"

bool_t
xdr_call_type (XDR *xdrs, call_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response_msg (XDR *xdrs, response_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_call_msg (XDR *xdrs, call_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_call_type (xdrs, &objp->ctype))
		 return FALSE;
	switch (objp->ctype) {
	case GET:
		 if (!xdr_string (xdrs, &objp->call_msg_u.filename, 128))
			 return FALSE;
		break;
	case QUIT:
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
